config/routes.rb
AveRails::Application.routes.draw do
  match '/',  :to => 'pages#home'
  match 'settings' => "users#edit",						:as => :settings
  match 'designers' => "users#index", 				:as => :designers
  match 'upload' => "collections#new", 			  :as => :upload
  match 'projects' => "projects#index",       :as => :projects
  match 'login' => "user_sessions#new",       :as => :login
  match 'logout' => "user_sessions#destroy",  :as => :logout
  match 'signup' => 'users#new', 							:as => :signup

  resources :user_sessions
  resources :projects 

  resources :collections do
      member do
        post :request
      end
  end
  
  resources :submissions do
      member do
        post :request
      end
  end

  resources :attachments
  resources :looks

  resources :users do
      member do
        post :follow
        post :unfollow
        get :following, :followers
      end
  end
  resources :relationships, :only => [:create, :destroy]
	resource  :user, :as => 'account'  # Convenience route

  root :to => 'pages#home'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :user_id, :title, :project_type, :client, :concept, :delivery_method, 
  								:street, :suite, :city, :state, :zip, :deadline, :return_by
  belongs_to :user
  has_many :submissions, :dependent => :destroy
  has_many :attachments, :dependent => :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	def new
  @project = Project.new
  end

  def create
  	@project = Project.new(params[:project])
  	if @project.save
  		flash[:notice] = "Your project has been posted."
  		redirect_to @project
  	else
  		render :action => :new
  	end
  end

	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
		@submission = Submission.new(params[:submission])
		
	end

  def edit
  	@project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end
end

app/views/projects/_form.html.erb
<%= form_for @project, :html=> { :multipart => true} do |f| %>
  <%= render "shared/error_messages", :target => @project %>
   <% f.hidden_field :user_id, :value => current_user.id %>
  <p>
    <%= f.label "What type of project are you posting?" %><br />
    <%= f.select :project_type, ["Commercial","Editorial","Red Carpet","Television","Theatre","Movie","Music Video","Public Work","Other"] %>
  </p>
  <p>
    <%= f.label "Who is the client?" %><br />
    <%= f.text_field :client %>
  </p>
  <p>
    <%= f.label "Project Title" %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label "When do you need these pieces by?" %><br />
    <%= f.datepicker "deadline" %> 
  </p>
  <p>
    <%= f.label "When will you return these pieces by?" %><br />
    <%= f.datepicker "return_by" %> 
  </p>
  <p>
    <%= f.label "What is the look or inspiration for this shoot?*" %><br />
    <%= f.text_area :concept %>
  </p>
  <strong>Handling - where you want pieces sent/delivered</strong> <br/>
  <p>
    <%= f.label "How would you prefer getting the pulled pieces?" %><br />
    <%= f.select :delivery_method, ["Mail","In Person Pickup","In Person Delivery","Schedule Meeting"] %>
  </p>
  <p>
    <%= f.label "Street Address" %><br />
    <%= f.text_field :street %>
  </p>
  <p>
    <%= f.label "Apt/Suite" %><br />
    <%= f.text_field :suite %>
  </p>
  <p>
    <%= f.label "City" %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label "State" %><br />    
    <%= f.select :state, us_states %>
  </p>
  <p>
    <%= f.label "Zip" %><br />
    <%= f.text_field :zip %>
  </p>
  <strong>Legal</strong>
  !add upload for legal contract.
 
  <p><%= f.submit "Post" %></p>
<% end %>

app/views/projects/index.html.erb
<% unless @projects.empty? %>
<% @projects.each do |project| %>
  <li>
  	<%= link_to project.title, project %>
  	<%= project.project_type %>
	</li>
<% end %>
<% else %>
There are no open projects at this time.
<% end %>

<%# if current_user.vip? %>
	<%= link_to "Post a Project", new_project_path %>
<%# end %>

app/views/projects/new.html.erb
<%= render :partial=>"form" %>

app/views/projects/show.html.erb
<%= @project.user_id %><p/>
<%= @project.title %><p/>
<%= @project.project_type %><p/>
<%= @project.client %><p/>
<%= @project.concept %><p/>
<%= @project.delivery_method %><p/>
<%= @project.deadline %><p/>
<%= @project.return_by %><p/>
<%= @project.street %><p/>
<%= @project.suite %><p/>
<%= @project.city %><p/>
<%= @project.state %><p/>
<%= @project.zip %><p/>

<%= render "submissions/form" %>