config/routes.rb
AveRails::Application.routes.draw do
  match '/',  :to => 'pages#home'
  match 'settings' => "users#edit",						:as => :settings
  match 'designers' => "users#index", 				:as => :designers
  match 'upload' => "collections#new", 			  :as => :upload
  match 'projects' => "projects#index",       :as => :projects
  match 'login' => "user_sessions#new",       :as => :login
  match 'logout' => "user_sessions#destroy",  :as => :logout
  match 'signup' => 'users#new', 							:as => :signup

  resources :user_sessions
  resources :projects 

  resources :collections do
      member do
        post :request
      end
  end
  
  resources :submissions do
      member do
        post :request
      end
  end

  resources :attachments
  resources :looks

  resources :users do
      member do
        post :follow
        post :unfollow
        get :following, :followers
      end
  end
  resources :relationships, :only => [:create, :destroy]
	resource  :user, :as => 'account'  # Convenience route

  root :to => 'pages#home'
end

app/views/layouts/_header.html.erb
<div class="header">
	<!--div class="header_container"></div-->
	<%= link_to "THE AVE", root_path, :class=>"header_logo" %>
	
	<% if current_user %>
		<span><%= link_to "Sign out", logout_path, :class=>"header_links" %></span>
		<span><%= link_to 'Settings', settings_path, :class=>"header_links" %></span>
		<span><%= link_to "Profile", current_user, :class=>"header_links" %></span>
		<span><%= link_to "Upload", upload_path, :class=>"header_links" %></span>
		<span><%= link_to "Projects", projects_path, :class=>"header_links" %></span>
		<span><%= link_to "Designers", designers_path, :class=>"header_links" %></span>
	<% else %>
		<span><%= link_to "Signup", signup_path, :class=>"header_links" %></span>
		<span><%= link_to "Signin", login_path, :class=>"header_links" %></span>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AveRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |key, value| %>
    <div id="flash" class="<%= key %>"><%= value %></div>
  <% end %>
<%= yield %>

</body>
</html>